"use client";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@mui/material";
import theme from "@/components/theme/theme";
import {Toaster} from "react-hot-toast";
import {createContext, Suspense, useContext, useState} from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const ChartContext = createContext({});
export default function RootLayout({children}) {
    const [code, setCode] = useState('');
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`} cz-shortcut-listen="true">
        {/*<Header />*/}
        <ChartContext.Provider value={{code, setCode}}>
            <Toaster/>
            <ThemeProvider theme={theme}>
                <Suspense>
                    {children}
                </Suspense>
            </ThemeProvider>
        </ChartContext.Provider>
        </body>
        </html>
    );
}
